### PR TITLE
fix nixrc documentation for graph_bound local_max [#22]

### LINKED ISSUE #22: Config graph_bound documentation inconsistent
https://nyx.torproject.org/#configuration says `graph_bound` is default `max_local` and options are `global_max`, `local_max`, `tight`

So… which is it, max_local or local_max? And to double check: max_global or global_max?

### PR DESCRIPTION
**Pull request by saizai**
Fixes #22

### CODE REVIEW

**Comment by atagar** [comment]
I apologize, I pushed this same fix before realizing there was a pull request.

**Comment by saizai** [comment]
Could you cite the commit here in for reference? Thanks!

**Comment by saizai** [comment]
PS in the future I suggest using @ mentions — eg @atagar rather than atagar. They should trigger a notification even in a commit message.

**Comment by saizai** [comment]
c099fe31266bc68f8551f93db9f5a95a6944c303

**Comment by saizai** [comment]
PPS I believe if your commit message and/or PR includes the word **Fixes**, it should autoclose the issue on merge. E.g. `Fixes #22`.

**Pull request closed without merging**
